build_from:
  aarch64: "arm64v8/debian:"
  armv7: "arm32v7/debian:"
  armhf: "arm32v5/debian:"
  amd64: "debian:"
  i386: "i386/debian:"
labels:
  org.opencontainers.image.title: "Meross Local Broker"
  org.opencontainers.image.description: "Implements Meross broker service locally."
  org.opencontainers.image.licenses: "Apache License 2.0"
  org.opencontainers.image.source: "https://github.com/dkhalife/ha-meross-local-broker"
